# ============================
# Project Metadata
# ============================
# Basic information about your Python project as defined by PEP 621

[project]
name = "Production-Grade-AI-Agentic-System"
version = "1.0.0"
description = "A production grade AI agentic system."
authors = [
    { name="rehamessa", email="rehamessa96@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
keywords = ["chatbot", "ai agentic system"]
dependencies = [
    "pydantic-settings>=2.15.0",
]
